name       : fontforge
homepage   : https://fontforge.github.io
version    : '20190413'
release    : 7
source     :
    - https://github.com/fontforge/fontforge/releases/download/20190413/fontforge-20190413.tar.gz : 6762a045aba3d6ff1a7b856ae2e1e900a08a8925ccac5ebf24de91692b206617
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.graphics
summary    : A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats
description: |
    A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pangoxft)
    - pkgconfig(pangocairo)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - intltool
    - libiconv-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -dm00755 $installdir/usr/share/icons/hicolor
    cp -R $workdir/desktop/2012/*x* $workdir/desktop/2012/scalable $installdir/usr/share/icons/hicolor/
