name       : fontforge
homepage   : https://fontforge.github.io
version    : 20160404
release    : 2
source     :
    - https://github.com/fontforge/fontforge/releases/download/20160404/fontforge-dist-20160404.tar.gz : 6c73a556030d985e166974e5d6025255290874c2d6bb349c9930b03f17b45bcd
license    : GPL-3.0
component  : multimedia.graphics
summary    : A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats.
description: |
    A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pangoxft)
    - pkgconfig(pangocairo)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(zlib)
    - intltool
    - libiconv-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm644 $workdir/desktop/fontforge.desktop $installdir/usr/share/applications/fontforge.desktop
    install -dm755 $installdir/usr/share/icons/hicolor
    cp -R $workdir/desktop/icons/*x* $workdir/desktop/icons/scalable $installdir/usr/share/icons/hicolor/
