name       : fontforge
homepage   : https://fontforge.org/
version    : '20190801'
release    : 8
source     :
    - https://github.com/fontforge/fontforge/archive/20190801.tar.gz : e4501de5bd8e7f6c68fe7d3abd4667bf44a07b981d342ffa00e8f42e155ce633
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : multimedia.graphics
summary    : A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats
description: |
    A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libspiro)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libuninameslist)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libzmq)
    - pkgconfig(python3)
    - pkgconfig(xft)
    - giflib-devel
    - intltool
    - libiconv-devel
setup      : |
    export PYTHON=python3
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -dm00755 $installdir/usr/share/icons/hicolor
    cp -R $workdir/desktop/2012/*x* $workdir/desktop/2012/scalable $installdir/usr/share/icons/hicolor/
