name       : fontforge
homepage   : https://fontforge.org/
version    : '20201107'
release    : 12
source     :
    - https://github.com/fontforge/fontforge/releases/download/20201107/fontforge-20201107.tar.xz : 68bcba8f602819eddc29cd356ee13fafbad7a80d19b652d354c6791343476c78
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : multimedia.graphics
summary    : A free (libre) font editor used to create, edit and convert fonts in
    OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats
description: |
    A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libspiro)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libuninameslist)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwoff2common)
    - pkgconfig(libzmq)
    - pkgconfig(python3)
    - pkgconfig(xft)
    - giflib-devel
    - intltool
    - libiconv-devel
libsplit   : no
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
