name       : fontforge
homepage   : https://fontforge.org/
version    : '20200314'
release    : 10
source     :
    - https://github.com/fontforge/fontforge/releases/download/20200314/fontforge-20200314.tar.xz : cd190b237353dc3f48ddca7b0b3439da8ec4fcf27911d14cc1ccc76c1a47c861
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : multimedia.graphics
summary    : A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats
description: |
    A free (libre) font editor used to create, edit and convert fonts in OpenType, TrueType, UFO, CID-keyed, Multiple Master, and many other formats.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libspiro)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libuninameslist)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwoff2common)
    - pkgconfig(libzmq)
    - pkgconfig(python3)
    - pkgconfig(xft)
    - giflib-devel
    - intltool
    - libiconv-devel
libsplit   : no
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
